In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Student_id': [1,2,3,4,5,6,7,8,9,10],
    'Name': ['Aryan','Anuj','Sufi','Samruddhi','Vaishu','Siddhi','Husain','Chinmay','Tanaya','Rosy'],
    'Age' : [20,20,np.nan,22,32,25,18,41,19,np.nan],
    'Gender' : ['Male','Male','Male','Female','Female','Female','Male','Male','Female','Female'],
    'Percentage' : [88,74,58,81,95,92,105,95,99,18],
    'Attendance' : [78,84,75,91,115,88,25,97,76,83],
    'Grade' : ['B','B','C','B','A','A','A','A','A','Z',]
    
}

In [5]:
df=pd.DataFrame(data)

In [7]:
df.head(10
       )

   Student_id       Name   Age  Gender  Percentage  Attendance Grade
0           1      Aryan  20.0    Male          88          78     B
1           2       Anuj  20.0    Male          74          84     B
2           3       Sufi   NaN    Male          58          75     C
3           4  Samruddhi  22.0  Female          81          91     B
4           5     Vaishu  32.0  Female          95         115     A
5           6     Siddhi  25.0  Female          92          88     A
6           7     Husain  18.0    Male         105          25     A
7           8    Chinmay  41.0    Male          95          97     A
8           9     Tanaya  19.0  Female          99          76     A
9          10       Rosy   NaN  Female          18          83     Z

In [8]:
df.isnull().sum()

Student_id    0
Name          0
Age           2
Gender        0
Percentage    0
Attendance    0
Grade         0
dtype: int64

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [10]:
df

   Student_id       Name     Age  Gender  Percentage  Attendance Grade
0           1      Aryan  20.000    Male          88          78     B
1           2       Anuj  20.000    Male          74          84     B
2           3       Sufi  24.625    Male          58          75     C
3           4  Samruddhi  22.000  Female          81          91     B
4           5     Vaishu  32.000  Female          95         115     A
5           6     Siddhi  25.000  Female          92          88     A
6           7     Husain  18.000    Male         105          25     A
7           8    Chinmay  41.000    Male          95          97     A
8           9     Tanaya  19.000  Female          99          76     A
9          10       Rosy  24.625  Female          18          83     Z

In [12]:
df['Age']=df['Age'].astype(int)

In [13]:
df

   Student_id       Name  Age  Gender  Percentage  Attendance Grade
0           1      Aryan   20    Male          88          78     B
1           2       Anuj   20    Male          74          84     B
2           3       Sufi   24    Male          58          75     C
3           4  Samruddhi   22  Female          81          91     B
4           5     Vaishu   32  Female          95         115     A
5           6     Siddhi   25  Female          92          88     A
6           7     Husain   18    Male         105          25     A
7           8    Chinmay   41    Male          95          97     A
8           9     Tanaya   19  Female          99          76     A
9          10       Rosy   24  Female          18          83     Z

In [15]:
df[df['Percentage'] > 100]

   Student_id    Name  Age Gender  Percentage  Attendance Grade
6           7  Husain   18   Male         105          25     A

In [16]:
df[df['Attendance'] > 100]

   Student_id    Name  Age  Gender  Percentage  Attendance Grade
4           5  Vaishu   32  Female          95         115     A

In [20]:
df[~df['Grade'].isin(['A','B','C','D','F'])]

   Student_id  Name  Age  Gender  Percentage  Attendance Grade
9          10  Rosy   24  Female          18          83     Z

In [21]:
df['Percentage'] = df['Percentage'].apply(lambda x: 100 if x > 100 else (0 if x < 0 else x))

In [26]:
df

   Student_id       Name  Age  Gender  Percentage  Attendance Grade
0           1      Aryan   20    Male          88          78     B
1           2       Anuj   20    Male          74          84     B
2           3       Sufi   24    Male          58          75     C
3           4  Samruddhi   22  Female          81          91     B
4           5     Vaishu   32  Female          95         100     A
5           6     Siddhi   25  Female          92          88     A
6           7     Husain   18    Male         100          25     A
7           8    Chinmay   41    Male          95          97     A
8           9     Tanaya   19  Female          99          76     A
9          10       Rosy   24  Female          18          83     F

In [23]:
df['Attendance'] = df['Attendance'].apply(lambda x: 100 if x > 100 else (0 if x < 0 else x))

In [25]:
df['Grade'] = df['Grade'].apply(lambda x : x if x in ['A','B','C','D','F'] else 'F')

In [29]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR 

df[df['Age'] > higher_limit]

   Student_id     Name  Age  Gender  Percentage  Attendance Grade
4           5   Vaishu   32  Female          95         100     A
7           8  Chinmay   41    Male          95          97     A

In [30]:
df['Age'] = df['Age'].apply(lambda x : df['Age'].median() if x > higher_limit else x)

In [31]:
df

   Student_id       Name   Age  Gender  Percentage  Attendance Grade
0           1      Aryan  20.0    Male          88          78     B
1           2       Anuj  20.0    Male          74          84     B
2           3       Sufi  24.0    Male          58          75     C
3           4  Samruddhi  22.0  Female          81          91     B
4           5     Vaishu  23.0  Female          95         100     A
5           6     Siddhi  25.0  Female          92          88     A
6           7     Husain  18.0    Male         100          25     A
7           8    Chinmay  23.0    Male          95          97     A
8           9     Tanaya  19.0  Female          99          76     A
9          10       Rosy  24.0  Female          18          83     F

In [32]:
minimum = df['Attendance'].min()
maximum = df['Attendance'].max()
df['Scaled Attendance'] = (df['Attendance'] - minimum)/(maximum - minimum)

In [33]:
df

,Student_id,Name,Age,Gender,Percentage,Attendance,Grade,Scaled Attendance
0,1,Aryan,20.0,Male,88,78,B,0.706667
1,2,Anuj,20.0,Male,74,84,B,0.786667
2,3,Sufi,24.0,Male,58,75,C,0.666667
3,4,Samruddhi,22.0,Female,81,91,B,0.880000
4,5,Vaishu,23.0,Female,95,100,A,1.000000
5,6,Siddhi,25.0,Female,92,88,A,0.840000
6,7,Husain,18.0,Male,100,25,A,0.000000
7,8,Chinmay,23.0,Male,95,97,A,0.960000
8,9,Tanaya,19.0,Female,99,76,A,0.680000
9,10,Rosy,24.0,Female,18,83,F,0.773333