In [1]:
import pandas as pd

In [2]:
data = {
    'age': [25, 30, 22, 40, 55, 60, 33, 28, 45, 50],
    'income': [50000, 60000, 45000, 70000, 80000, 90000, 65000, 62000, 75000, 85000],
    'age_group': ['20-30', '30-40', '20-30', '40-50', '50-60', '50-60', '30-40', '20-30', '40-50', '50-60']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   age  income age_group
0   25   50000     20-30
1   30   60000     30-40
2   22   45000     20-30
3   40   70000     40-50
4   55   80000     50-60
5   60   90000     50-60
6   33   65000     30-40
7   28   62000     20-30
8   45   75000     40-50
9   50   85000     50-60

In [7]:
df.groupby('age_group')['income'].describe()

,count,mean,std,min,25%,50%,75%,max
age_group,,,,,,,,
20-30,3.0,52333.333333,8736.894948,45000.0,47500.0,50000.0,56000.0,62000.0
30-40,2.0,62500.000000,3535.533906,60000.0,61250.0,62500.0,63750.0,65000.0
40-50,2.0,72500.000000,3535.533906,70000.0,71250.0,72500.0,73750.0,75000.0
50-60,3.0,85000.000000,5000.000000,80000.0,82500.0,85000.0,87500.0,90000.0

In [21]:
data1 = {
    'age': [25, 30, 25, 40, 55, 60, 33, 28, 45, 50, 25, 30, 28, 30, 25],
    'income': [50000, 60000, 50000, 70000, 80000, 90000, 65000, 62000, 75000, 85000, 50000, 60000, 62000, 70000, 75000],
    'age_group': ['20-30', '30-40', '20-30', '40-50', '50-60', '50-60', '30-40', '20-30', '40-50', '50-60', '20-30', '30-40', '20-30', '30-40', '20-30']
}

# Define data in DataFrame
df = pd.DataFrame(data1)

In [22]:
df.groupby('age_group')['income'].describe()

,count,mean,std,min,25%,50%,75%,max
age_group,,,,,,,,
20-30,6.0,58166.666667,10127.520262,50000.0,50000.0,56000.0,62000.0,75000.0
30-40,4.0,63750.000000,4787.135539,60000.0,60000.0,62500.0,66250.0,70000.0
40-50,2.0,72500.000000,3535.533906,70000.0,71250.0,72500.0,73750.0,75000.0
50-60,3.0,85000.000000,5000.000000,80000.0,82500.0,85000.0,87500.0,90000.0

In [23]:
df.groupby('age_group')['income'].median()

age_group
20-30    56000.0
30-40    62500.0
40-50    72500.0
50-60    85000.0
Name: income, dtype: float64

In [24]:
print("Column Names:", df.columns)

Column Names: Index(['age', 'income', 'age_group'], dtype='object')

In [27]:
m_age = df['age'].mode()
print(m_age.values)
m_income = df['income'].mode()
print(m_income)

[25]
0    50000
Name: income, dtype: int64

In [30]:
grouped = df.groupby('age_group')
income_list = grouped['income'].apply(list)
print(income_list)

age_group
20-30    [50000, 50000, 62000, 50000, 62000, 75000]
30-40                  [60000, 65000, 60000, 70000]
40-50                                [70000, 75000]
50-60                         [80000, 90000, 85000]
Name: income, dtype: object

In [31]:
# PS2

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [6]:
grouped = df.groupby('variety')
for name, group in grouped:
    print(f"Species : {name}")
    print(group.describe())
# print(grouped.describe())

# print(df.groupby('variety').describe())

Species : Setosa
       sepal.length  sepal.width  petal.length  petal.width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000
Species : Versicolor
       sepal.length  sepal.width  petal.length  petal.width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000
Species : Virginica
       sepal.length  sepal.width  petal.length  petal.width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000

In [45]:
percentile = df.groupby('variety').quantile([0.25,0.5,0.75])

In [56]:
print(grouped.describe())
print(percentile)

           sepal.length                                              \
                  count   mean       std  min    25%  50%  75%  max
variety
Setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal.width         ... petal.length      petal.width         \
                 count   mean  ...          75%  max       count   mean
variety                        ...
Setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
Versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
Virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
variety
Setosa      0.105386  0.1  0.2  0.2  0.3  0.6
Versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]
                 sepal.length  sepal.width  petal.length  petal.width
variety
Setosa     0.25         4.800        3.200         1.400          0.2
           0.50         5.000        3.400         1.500          0.2
           0.75         5.200        3.675         1.575          0.3
Versicolor 0.25         5.600        2.525         4.000          1.2
           0.50         5.900        2.800         4.350          1.3
           0.75         6.300        3.000         4.600          1.5
Virginica  0.25         6.225        2.800         5.100          1.8
           0.50         6.500        3.000         5.550          2.0
           0.75         6.900        3.175         5.875          2.3

In [57]:
# Group the data by variety; Select sepal.width column for each of the groups created; Display summary statistics
summary_stats_species = df.groupby('variety')['sepal.width'].describe()

print("\nSummary Statistics by Species for Sepal Width:")
print(summary_stats_species)

Summary Statistics by Species for Sepal Width:
            count   mean       std  min    25%  50%    75%  max
variety
Setosa       50.0  3.428  0.379064  2.3  3.200  3.4  3.675  4.4
Versicolor   50.0  2.770  0.313798  2.0  2.525  2.8  3.000  3.4
Virginica    50.0  2.974  0.322497  2.2  2.800  3.0  3.175  3.8

In [7]:
# Group by variety and compute the median for numeric columns
# median_values = 
df.groupby('variety').median()

# print("Median Values by Species:")
# print(median_values)

            sepal.length  sepal.width  petal.length  petal.width
variety
Setosa               5.0          3.4          1.50          0.2
Versicolor           5.9          2.8          4.35          1.3
Virginica            6.5          3.0          5.55          2.0

In [59]:
# Group the data by variety; Select sepal.width column for each of the groups created; Display median
median_sepal_length = df.groupby('variety')['sepal.length'].median()
print("Median Sepal Length by Species:")
print(median_sepal_length)

Median Sepal Length by Species:
variety
Setosa        5.0
Versicolor    5.9
Virginica     6.5
Name: sepal.length, dtype: float64

In [60]:
# Calculate & print mode for sepal.width
mode_width = df['sepal.width'].mode()
print(f"Mode of Width: {mode_width.values}")

Mode of Width: [3.]